@startuml



while (Avijjā?)              is (āma)
if    (Viññāṇa?)             then (āma)
if    (Saṅkhāra?)            then (āma)
if    (Nāmarūpa?)            then (āma)
if    (Saḷāyatana)           then (āma)
if    (Phassa?)              then (āma)
if    (Vedanā?)              then (āma)
if    (Taṇhā?)               then (āma)
if    (Bhava?)               then (āma)
if    (Jāti?)                then (āma)
if    (Bhava?)               then (āma)
if    (Jarāmaraṇa?)          then (āma)
:Dukkha;
detach
endif
endif
endif
endif
endif
endif
endif
endif
endif
endif
endif
endwhile
stop


@enduml