@startuml

while (Avijjā?)              is (āma)
if    (Viññāṇa?)             then (āma)

repeat
    :Saṅkhāra;
    :Nāmarūpa;
repeat while (aniṭṭhita) is (na)
:Saḷāyatana;

if    (Phassa?)              then (āma)
if    (Vedanā?)              then (āma)
if    (Taṇhā?)               then (āma)
if    (Bhava?)               then (āma)
if    (Jāti?)                then (āma)
if    (Bhava?)               then (āma)
if    (Jarāmaraṇa?)

:Dukkha;
stop

endif
endif
endif
endif
endif
endif
endif
endif

endwhile

stop
    
@enduml