name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt install plantuml

    - name: Build
      run: make

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.1.1
      with:
        # Artifact name
        name: Dependent Origination Image File
        # Destination path
        path: dependent-origination.png
    
